### ISSUE TITLE
You exceeded your current quota

### ISSUE THREAD

**Issue by maslick** [ibuildthecloud/catgpt#1]
Everytime I run catgpt I get an `error, status code: 429, message: You exceeded your current quota, please check your plan and billing details.`

Looks strange, since I haven't even run chat GPT for the whole day prior to testing catgpt. FYI: I've got the Plus plan ($20/month)

**Comment by ibuildthecloud** [comment]
ChatGPT and OpenAI API access are treated as two different products.  It's kind of weird. One has nothing to do with the other.  For API access you have to go to https://platform.openai.com/account/billing/overview and typically fund the account. Add $10 to it or some amount like that.  So the $20/mo you pay for ChatGPT does not go towards API access and the usages between the two don't impact each other.
